In [7]:
import numpy as np

#### Creating Array

In [9]:
ar1 = np.array([1,2,3])
ar1

array([1, 2, 3])

In [10]:
type(ar1)

numpy.ndarray

In [13]:
ar1.ndim

1

In [19]:
ar2 = np.zeros((2,2) ) #2 rows, 2 columns matrix should be filled with zeroes
ar2

array([[0., 0.],
       [0., 0.]])

In [14]:
ar2.ndim # return no.of dimensions array

2

In [25]:
np.random.random((3,3))

array([[0.89080109, 0.4420096 , 0.91849108],
       [0.2244886 , 0.18275159, 0.59180751],
       [0.04832671, 0.2145513 , 0.80962155]])

#### Array Initializatioin

In [28]:
np.full((2,2),5) # fill the matrix 2,2 with value 5

array([[5, 5],
       [5, 5]])

In [31]:
np.arange(5,20,2) # start = 5, end = 20 , interval = 2
# end is not going to be included

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
np.linspace(5,20,2) # start = 5, end = 20 , count of digits = 2
# generate 2 data points from 5 till 20 with equal intervals in between them

array([ 5., 20.])

In [37]:
np.linspace(5,20,3)

array([ 5. , 12.5, 20. ])

#### Array Inspection 

In [40]:
ar1 = np.full((3,2),2)
ar1

array([[2, 2],
       [2, 2],
       [2, 2]])

In [41]:
ar1.shape # no.of rows and columns 3 rows and 2 columns

(3, 2)

In [42]:
ar1.size # count no.of elements

6

In [44]:
ar1.ndim # no.of dimensions

2

In [45]:
ar1.dtype

dtype('int32')

In [46]:
### Reshape

In [47]:
ar1

array([[2, 2],
       [2, 2],
       [2, 2]])

In [48]:
ar1.shape # 3 rows and 2 columns

(3, 2)

In [ ]:
# We have total 6 elements so when changing shape the new shape should incorporate all the elements 

In [ ]:
# rows * column = ar1.size

In [54]:
ar1.shape = (2,3) # 2 rows and 3 columns

In [55]:
ar1

array([[2, 2, 2, 2, 2, 2]])

In [56]:
ar1.shape = (6,1) # 6 rows and 1 column
ar1

array([[2],
       [2],
       [2],
       [2],
       [2],
       [2]])

In [57]:
ar1.ndim

2

In [61]:
ar1 = np.arange(30)

In [65]:
ar2 = ar1.reshape(2,5,3)
ar2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [66]:
ar2.ndim

3

#### Array mathematics

In [79]:
ar1 = np.array([1,2,3])
ar1

array([1, 2, 3])

In [80]:
np.sum(ar1) # add all the elements
# 3+2+1

6

In [70]:
ar1 = np.array([[10,5],
               [6,8]])
ar1

array([[10,  5],
       [ 6,  8]])

In [75]:
np.sum(ar1,axis = 0) # axis = 0 --> take the sum at row level
# 10+6,5+8

array([16, 13])

In [76]:
np.sum(ar1,axis = 1) # axis = 0 --> take the sum at column level
# 10+5,6+8

array([15, 14])

In [82]:
a = 20
b = 5

In [83]:
print(np.subtract(a,b))

15


In [84]:
print(np.multiply(a,b))
print(np.divide(a,b))

100
4.0


In [85]:
print(np.exp(a))
print(np.sqrt(a))
print(np.log(a))

485165195.4097903
4.47213595499958
2.995732273553991


In [86]:
ar1 = np.array([1,2,3])
ar2 = np.array([1,2,3])
ar3 = np.array([1,2,4])

In [87]:
np.equal(ar1,ar2) # it compares at a element wise in sequence 

array([ True,  True,  True])

In [88]:
np.equal(ar1,ar3)

array([ True,  True, False])

In [89]:
np.array_equal(ar1,ar2) # it compares an entire array

True

In [90]:
np.array_equal(ar1,ar3)

False

#### Array Indexing

In [92]:
ar1 = np.array([10,20,30,40,50])
ar1

array([10, 20, 30, 40, 50])

In [93]:
ar1[1:4]

array([20, 30, 40])

In [97]:
ar1 = np.array([['a','b','c','10'],
               ['d','e','f','20'],
               ['g','h','i','30'],
               ['j','k','l','40']])
print(ar1)

[['a' 'b' 'c' '10']
 ['d' 'e' 'f' '20']
 ['g' 'h' 'i' '30']
 ['j' 'k' 'l' '40']]


In [107]:
ar1[2:4,0:3]

array([['g', 'h', 'i'],
       ['j', 'k', 'l']], dtype='<U2')

In [100]:
ar1[2]

array(['g', 'h', 'i', '30'], dtype='<U2')

In [101]:
ar1[1:2] # start = 1, end-1 = 2-1  = 1 

array([['d', 'e', 'f', '20']], dtype='<U2')

In [102]:
ar1[1:3]

array([['d', 'e', 'f', '20'],
       ['g', 'h', 'i', '30']], dtype='<U2')

In [104]:
ar1[:,1] # 1 st column 

array(['b', 'e', 'h', 'k'], dtype='<U2')

In [105]:
ar1[:,1:2]

array([['b'],
       ['e'],
       ['h'],
       ['k']], dtype='<U2')

In [106]:
ar1[:,1:3]

array([['b', 'c'],
       ['e', 'f'],
       ['h', 'i'],
       ['k', 'l']], dtype='<U2')

In [98]:
ar1[1:3,1:3]

array([['e', 'f'],
       ['h', 'i']], dtype='<U2')

#### Array Manipulation

In [109]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[10,20],[30,40]])

In [110]:
print(ar1)
print(ar2)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [114]:
np.concatenate((ar1,ar2), axis = 0) # 0 for rows 
                                    # 1 for columns 

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

In [115]:
np.concatenate((ar1,ar2), axis = 1) 

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [116]:
np.vstack((ar1,ar2)) # np.concatenate axis = 0 

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

In [117]:
np.hstack((ar1,ar2)) # np.concatenate axis = 1

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [118]:
np.column_stack((ar1,ar2))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40]])

In [119]:
ar2 = np.hstack((ar1,ar2,ar1))
ar2

array([[ 1,  2, 10, 20,  1,  2],
       [ 3,  4, 30, 40,  3,  4]])

In [125]:
np.hsplit(ar2,2)

[array([[ 1,  2, 10],
        [ 3,  4, 30]]),
 array([[20,  1,  2],
        [40,  3,  4]])]