**Numpy Handson**
Numpy is upto 50 times more faster than list while working on arrays

In [4]:
'''1. Create a numpy array with numpy.array module and with a data type integer and float.'''

import numpy as np

arr1=np.array([1,2,3,4,5],dtype='int')
print(arr1)
print(arr1.dtype)

[1 2 3 4 5]
int64


In [6]:
arr2=np.array([1,2,3,4,5],dtype='float')
print(arr2)
print(arr2.dtype)

[1. 2. 3. 4. 5.]
float64


In [12]:
arr3=np.array([1.0,2.0,3.0,4.0,5.7])
print(arr3.dtype)

float64


In [8]:
arr3=np.array([1,2,5.6,6.8,"Xyz"])
print(arr3)
print(arr3.dtype)

['1' '2' '5.6' '6.8' 'Xyz']
<U32


In [10]:
arr3=np.array(["xyz","abc","pqr"])
print(arr3.dtype)

<U3


In [19]:
'''2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.
'''

arr=np.zeros((2,3),dtype="int")+3
arr

array([[3, 3, 3],
       [3, 3, 3]])

In [22]:
arr=np.ones((4,4),dtype="int")*3
arr

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [41]:
arr=np.full((2,3,),1)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
# use four square brackets

arr=np.array([[[[1,1],[1,1],[1,1]]]])
arr


array([[[[1, 1],
         [1, 1],
         [1, 1]]]])

In [27]:
print(arr.ndim)

4


In [33]:
# how to create 0d array
arr=np.array(34)
print(arr)
print(arr.ndim)

# how to create 1d array
arr2=np.array([23,45,67,89,90])
print(arr2)
print(arr2.ndim)

34
0
[23 45 67 89 90]
1


In [39]:
'''3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.'''

# in identity matrix all diagnol values will be 1 and all non diagonal values will be 0

arr2=np.identity(2,dtype='int')
print(arr2)

arr3=np.identity(3,dtype='int')
print(arr3)

arr4=np.identity(4,dtype='int')
print(arr4)


arr5=np.eye(2,3,dtype='int')
print(arr5)

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0]
 [0 1 0]]


In [43]:
'''4. Create a numpy array with shape 2x5 that has all the elements as zero.
5. Create a numpy array that has the shape 3x5 and all the elements are 5.
7. Create a numpy array with a shape 3x3 that has all elements as 1.'''
arr=np.full((3,5),5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [46]:
'''6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.'''

arr1=np.random.randint(0,101,size=(5,5))
print(arr1)

[[28 76 48 61 69]
 [97 32 25 57 24]
 [62 59 96 44 81]
 [46 90 55 49 22]
 [42 95 11 99 65]]


In [47]:
#(6,4)=6*4=24

arr1=np.random.randint(0,101,25)
print(arr1)

[98 65 43 21 12 29 83  6 27 10 71  4 85  3 44 78 84 28 32 65 56 63 95 87
 61]


In [48]:
'''8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.'''

arr1=np.random.randint(0,101,size=(2,3))
print(arr1)

[[ 0 29 12]
 [78 55 91]]


In [49]:
newarr=arr1.reshape(3,2)
print(newarr)


[[ 0 29]
 [12 78]
 [55 91]]


In [56]:
arr1=np.array([[1,2,3,4],[4,5,6,6],[7,8,9,9]])
print(arr1)
print(arr1.shape)

# now i want to change the shapw to

arr1=arr1.reshape(6,2)
print(arr1)

[[1 2 3 4]
 [4 5 6 6]
 [7 8 9 9]]
(3, 4)
[[1 2]
 [3 4]
 [4 5]
 [6 6]
 [7 8]
 [9 9]]


In [77]:
'''9. step 1- Create a random array, with the range 0-1000, with a size 50
step 2- Perform the following operations on the same.
a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.'''

arr1=np.random.randint(0,1001,50)
print(arr1)

#a. Print the first ten elements of the array.
print( arr1[ :10])

#b  Print the last ten elements of the array
print(arr1[-10:])
print(arr1[40:])

#c. Print the elements from the indexes 10-25
print(arr1[10:26])

#d. Print the element at the index 22
print(arr1[22])

#e. Print the whole array using negative indexing.

print(arr1[-50: ]) # same order using -ve indexing
print(arr1[ : ]) # same  order using +ve index  - not correct due to question
print(arr1[ : : -1]) # reverse order using -ve indexing

#f. Print the last ten elements of the array, using negative indexing
print("--------------------------")
print(arr1[-10:])
print(arr1[-50:-40]) # wrong way
print(arr1[-1:-11:-1])

[301 146  30 732 133 194 463 470 481 257 459 847 276 989  14 736 654 691
 343 897 326 998 363 376 925 436   9 499 368  11 911 284 477 408 367 480
 404  72 520 777 416 850 244  23 224 182 460 212   2 601]
[301 146  30 732 133 194 463 470 481 257]
[416 850 244  23 224 182 460 212   2 601]
[416 850 244  23 224 182 460 212   2 601]
[459 847 276 989  14 736 654 691 343 897 326 998 363 376 925 436]
363
[301 146  30 732 133 194 463 470 481 257 459 847 276 989  14 736 654 691
 343 897 326 998 363 376 925 436   9 499 368  11 911 284 477 408 367 480
 404  72 520 777 416 850 244  23 224 182 460 212   2 601]
[301 146  30 732 133 194 463 470 481 257 459 847 276 989  14 736 654 691
 343 897 326 998 363 376 925 436   9 499 368  11 911 284 477 408 367 480
 404  72 520 777 416 850 244  23 224 182 460 212   2 601]
[601   2 212 460 182 224  23 244 850 416 777 520  72 404 480 367 408 477
 284 911  11 368 499   9 436 925 376 363 998 326 897 343 691 654 736  14
 989 276 847 459 257 481 470 463 194 133 732  

In [85]:
'''10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending orde'''

data=[1,2,3,4,5]
arr1=np.array(data)
print(arr1)

#Insert the element 6 at the end of the array.
newarr=np.append(arr1,6)
print(newarr)
#b. Insert the element 10 at the beginning of the array.
newarr=np.insert(newarr,0,10)
print(newarr)
'''c. Insert the element 30, before element 4.
d. Update the element 5 as 50.
HOMEWORK'''


# e. Delete the element 3 in the updated array.
newarr=np.delete(newarr,3)  #(array name , index at which element is present)
print(newarr)

# f -Create a function to search for the element 30.

def search(newarr,element):
  if element in newarr:
    print("present")
  else:
    print("not present")

# call our function

search(newarr,100)


[1 2 3 4 5]
[1 2 3 4 5 6]
[10  1  2  3  4  5  6]
[10  1  2  4  5  6]
not present


In [86]:
# g. Sort the array in ascending orde''
newarr.sort()

In [87]:
print(newarr)

[ 1  2  4  5  6 10]
